### ISSUE TITLE
Mod Failed to load on launch

### ISSUE THREAD

**Issue by Pricefield7x7** [CreeperHost/SoulShards#7]
-- MOD soulshards --
Details:
	Mod File: soulshards-1.19-1.3.2.jar
	Failure message: SoulShards (soulshards) has failed to load correctly
		java.lang.NoSuchFieldError: ENTITIES
	Mod Version: 1.19-1.3.2
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchFieldError: ENTITIES
Stacktrace:
	at net.creeperhost.soulshardsrespawn.core.ConfigSoulShards$ConfigEntityList.getDefaults(ConfigSoulShards.java:188) ~[soulshards-1.19-1.3.2.jar%23186!/:1.19-1.3.2] {re:classloading}
	at net.creeperhost.soulshardsrespawn.core.ConfigSoulShards$ConfigEntityList.<init>(ConfigSoulShards.java:177) ~[soulshards-1.19-1.3.2.jar%23186!/:1.19-1.3.2] {re:classloading}
	at net.creeperhost.soulshardsrespawn.core.ConfigSoulShards.<init>(ConfigSoulShards.java:31) ~[soulshards-1.19-1.3.2.jar%23186!/:1.19-1.3.2] {re:classloading}
	at net.creeperhost.soulshardsrespawn.SoulShards.<clinit>(SoulShards.java:28) ~[soulshards-1.19-1.3.2.jar%23186!/:1.19-1.3.2] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.98.jar%23198!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.98.jar%23197!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by juanmanuelrmarano** [comment]
Hello! I'm having exactly the same error, were you able to solve it?

**Comment by Eydanito** [comment]
Did anyone find a solution to this?

**Comment by gigabit101** [comment]
This broke in one of the Forge updates, It will be fixed as soon as forge pushes a release build

**Comment by gigabit101** [comment]
Fixed in latest release
